# Generated by Django 4.1.3 on 2022-11-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=[''], max_length=100),
            preserve_default=False,
        ),
    ]
