# Generated by Django 4.1.3 on 2022-11-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
