# Generated by Django 4.1.3 on 2022-12-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.CharField(default='New10', max_length=100),
        ),
    ]
