# Generated by Django 4.1.3 on 2022-12-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discount',
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.CharField(default='New10', max_length=100),
        ),
    ]
