# Generated by Django 4.1.3 on 2022-12-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_user_discount_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
